id: I70EBA636
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:37:10+00:00'
last_modified: '2022-06-09T08:14:23.669501+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB5977
  title: 'རྗེ་བཙུན་བླ་མ་ཤཱཀྱ་ཤྲཱི་ཛྙཱ་ནའི་རྣམ་ཐར་། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FE73:
      image_group_id: I1PD28141
      title: Volume 1 of rje btsun bla ma shAkya shrI dz+nyA na'i rnam thar
      total_pages: 171
      order: 1
      base_file: FE73.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
