id: P007978
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:52:56.792345
source_metadata:
  id: bdr:W2DB5977
  title: 'རྗེ་བཙུན་བླ་མ་ཤཱཀྱ་ཤྲཱི་ཛྙཱ་ནའི་རྣམ་ཐར་། '
  author: ''
  volumes:
    62fbf5c3c1244585aa4248638a07c7ef:
      image_group_id: I1PD28141
      title: Volume 1 of rje btsun bla ma shAkya shrI dz+nyA na'i rnam thar
      volume_number: 1
      total_pages: 171
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
