id: P007978
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB5977
  title: 'རྗེ་བཙུན་བླ་མ་ཤཱཀྱ་ཤྲཱི་ཛྙཱ་ནའི་རྣམ་ཐར་། '
  author: ''
  volumes:
    57beb3369a594af2a84f30c18b1a5a81:
      image_group_id: I1PD28141
      title: ''
      volume_number: 1
      total_pages: 171
ebook_metadata:
  title: 'རྗེ་བཙུན་བླ་མ་ཤཱཀྱ་ཤྲཱི་ཛྙཱ་ནའི་རྣམ་ཐར་། '
  author: ''
  sku: P007978
  cover: cover.jpg
  layers:
  - pagination
